### ISSUE TITLE
No values received since may in iphone adapter

### ISSUE THREAD

**Issue by DutchmanNL** [soef/ioBroker.find-my-iphone#8]
have this adapter installed for several months in beginning all looked quite OK, but now since may no new data is received.

Just made a fresh installation today, login is accepted also with 2 factor authentication but no values received.

debug:

`

find-my-iphone.0 | 2017-07-15 23:38:53.905 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154733902,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
-- | -- | -- | --
find-my-iphone.0 | 2017-07-15 23:38:53.905 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154733902,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:38:53.905 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":211,"ack":true,"ts":1500154733901,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154733901}
find-my-iphone.0 | 2017-07-15 23:38:53.905 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.93,"ack":true,"ts":1500154733901,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154733901}
find-my-iphone.0 | 2017-07-15 23:38:53.905 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154733901,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:38:53.905 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":44.67,"ack":true,"ts":1500154733901,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154718890}
find-my-iphone.0 | 2017-07-15 23:38:53.904 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154733900,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:53.904 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154733900,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154718891,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154718891,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":196,"ack":true,"ts":1500154718891,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154718891}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.76,"ack":true,"ts":1500154718891,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154718891}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154718891,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":44.67,"ack":true,"ts":1500154718890,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154718890}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154718890,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:38.892 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154718890,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:23.876 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154703876,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:38:23.876 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154703876,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:38:23.876 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":181,"ack":true,"ts":1500154703876,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154703876}
find-my-iphone.0 | 2017-07-15 23:38:23.875 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.55,"ack":true,"ts":1500154703875,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154703875}
find-my-iphone.0 | 2017-07-15 23:38:23.875 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154703875,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:38:23.875 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.96,"ack":true,"ts":1500154703875,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154703875}
find-my-iphone.0 | 2017-07-15 23:38:23.874 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154703874,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:23.874 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154703874,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:08.871 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154688871,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:38:08.870 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154688870,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:38:08.870 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":166,"ack":true,"ts":1500154688870,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154688870}
find-my-iphone.0 | 2017-07-15 23:38:08.870 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.32,"ack":true,"ts":1500154688870,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154688870}
find-my-iphone.0 | 2017-07-15 23:38:08.870 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154688870,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:38:08.870 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.45,"ack":true,"ts":1500154688869,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154688869}
find-my-iphone.0 | 2017-07-15 23:38:08.868 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154688868,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:38:08.868 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154688868,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:53.855 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154673855,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:37:53.855 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154673854,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:37:53.854 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":151,"ack":true,"ts":1500154673854,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154673854}
find-my-iphone.0 | 2017-07-15 23:37:53.854 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":17.07,"ack":true,"ts":1500154673854,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154673854}
find-my-iphone.0 | 2017-07-15 23:37:53.853 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154673853,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:37:53.853 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":44.16,"ack":true,"ts":1500154673853,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154673853}
find-my-iphone.0 | 2017-07-15 23:37:53.852 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154673852,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:53.852 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154673852,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:38.853 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154658853,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:37:38.853 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154658853,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:37:38.853 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":136,"ack":true,"ts":1500154658853,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154658853}
find-my-iphone.0 | 2017-07-15 23:37:38.853 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.87,"ack":true,"ts":1500154658853,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154658853}
find-my-iphone.0 | 2017-07-15 23:37:38.852 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154658852,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:37:38.852 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.9,"ack":true,"ts":1500154658852,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154658852}
find-my-iphone.0 | 2017-07-15 23:37:38.851 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154658851,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:38.851 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154658851,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:23.842 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154643842,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:37:23.841 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154643841,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:37:23.841 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":121,"ack":true,"ts":1500154643841,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154643841}
find-my-iphone.0 | 2017-07-15 23:37:23.841 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.68,"ack":true,"ts":1500154643841,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154643841}
find-my-iphone.0 | 2017-07-15 23:37:23.841 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154643841,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:37:23.841 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.64,"ack":true,"ts":1500154643841,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154628825}
find-my-iphone.0 | 2017-07-15 23:37:23.840 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154643840,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:23.840 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154643840,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:08.828 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154628828,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:37:08.828 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154628828,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:37:08.828 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":106,"ack":true,"ts":1500154628827,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154628827}
find-my-iphone.0 | 2017-07-15 23:37:08.825 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.47,"ack":true,"ts":1500154628825,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154628825}
find-my-iphone.0 | 2017-07-15 23:37:08.825 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154628825,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:37:08.825 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.64,"ack":true,"ts":1500154628825,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154628825}
find-my-iphone.0 | 2017-07-15 23:37:08.825 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154628825,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:37:08.825 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154628824,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:53.821 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154613821,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:36:53.821 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154613821,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:36:53.821 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":91,"ack":true,"ts":1500154613821,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613821}
find-my-iphone.0 | 2017-07-15 23:36:53.820 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.28,"ack":true,"ts":1500154613820,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:36:53.820 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":22,"ack":true,"ts":1500154613820,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:36:53.820 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.39,"ack":true,"ts":1500154613820,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154613820}
find-my-iphone.0 | 2017-07-15 23:36:53.820 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154613820,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:53.819 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154613819,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:38.809 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154598809,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:36:38.809 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154598809,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:36:38.808 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":76,"ack":true,"ts":1500154598808,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154598808}
find-my-iphone.0 | 2017-07-15 23:36:38.808 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":16.36,"ack":true,"ts":1500154598808,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154598808}
find-my-iphone.0 | 2017-07-15 23:36:38.808 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":23,"ack":true,"ts":1500154598808,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553776}
find-my-iphone.0 | 2017-07-15 23:36:38.803 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.34,"ack":true,"ts":1500154598803,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154598803}
find-my-iphone.0 | 2017-07-15 23:36:38.803 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154598803,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:38.803 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154598803,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:23.827 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154583827,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:36:23.827 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154583827,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:36:23.827 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":61,"ack":true,"ts":1500154583826,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154583826}
find-my-iphone.0 | 2017-07-15 23:36:23.826 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":18.25,"ack":true,"ts":1500154583826,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154583826}
find-my-iphone.0 | 2017-07-15 23:36:23.826 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":23,"ack":true,"ts":1500154583826,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553776}
find-my-iphone.0 | 2017-07-15 23:36:23.825 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":44.92,"ack":true,"ts":1500154583825,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154583825}
find-my-iphone.0 | 2017-07-15 23:36:23.820 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154583820,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:23.820 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154583820,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:08.795 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154568794,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:36:08.794 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154568794,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:36:08.794 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":46,"ack":true,"ts":1500154568794,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154568794}
find-my-iphone.0 | 2017-07-15 23:36:08.794 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":17.96,"ack":true,"ts":1500154568794,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154568794}
find-my-iphone.0 | 2017-07-15 23:36:08.793 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":23,"ack":true,"ts":1500154568793,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553776}
find-my-iphone.0 | 2017-07-15 23:36:08.792 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":44.71,"ack":true,"ts":1500154568792,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154568792}
find-my-iphone.0 | 2017-07-15 23:36:08.791 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154568791,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:36:08.791 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154568791,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:53.778 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154553778,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:35:53.777 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154553777,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:35:53.777 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":31,"ack":true,"ts":1500154553777,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553777}
find-my-iphone.0 | 2017-07-15 23:35:53.777 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":17.72,"ack":true,"ts":1500154553777,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553777}
find-my-iphone.0 | 2017-07-15 23:35:53.777 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":23,"ack":true,"ts":1500154553776,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553776}
find-my-iphone.0 | 2017-07-15 23:35:53.776 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":43.95,"ack":true,"ts":1500154553776,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154553776}
find-my-iphone.0 | 2017-07-15 23:35:53.776 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154553776,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:53.775 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154553775,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:38.776 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154538776,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:35:38.776 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154538776,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:35:38.775 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":16,"ack":true,"ts":1500154538775,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154538775}
find-my-iphone.0 | 2017-07-15 23:35:38.775 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":21.14,"ack":true,"ts":1500154538775,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154538775}
find-my-iphone.0 | 2017-07-15 23:35:38.775 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":36,"ack":true,"ts":1500154538775,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154538775}
find-my-iphone.0 | 2017-07-15 23:35:38.775 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":53.17,"ack":true,"ts":1500154538775,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154538775}
find-my-iphone.0 | 2017-07-15 23:35:38.774 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154538774,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:38.774 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154538774,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:23.781 | debug | redis psubscribe io.find-my-iphone.0.*
find-my-iphone.0 | 2017-07-15 23:35:23.774 | debug | redis mget 33 33
find-my-iphone.0 | 2017-07-15 23:35:23.769 | debug | redis publish io.system.adapter.find-my-iphone.0.prevVersion {"val":"0.2.8","ack":true,"ts":1500154523768,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523768}
find-my-iphone.0 | 2017-07-15 23:35:23.767 | debug | redis mget 1 1
find-my-iphone.0 | 2017-07-15 23:35:23.759 | debug | redis get system.adapter.find-my-iphone.0.prevVersion ok: null
find-my-iphone.0 | 2017-07-15 23:35:23.759 | debug | redis publish io.system.adapter.find-my-iphone.0.outputCount {"val":8,"ack":true,"ts":1500154523758,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523758}
find-my-iphone.0 | 2017-07-15 23:35:23.757 | debug | redis publish io.system.adapter.find-my-iphone.0.inputCount {"val":0,"ack":true,"ts":1500154523757,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:35:23.757 | debug | redis publish io.system.adapter.find-my-iphone.0.uptime {"val":1,"ack":true,"ts":1500154523757,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523757}
find-my-iphone.0 | 2017-07-15 23:35:23.756 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapUsed {"val":19.04,"ack":true,"ts":1500154523756,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523756}
find-my-iphone.0 | 2017-07-15 23:35:23.756 | debug | redis publish io.system.adapter.find-my-iphone.0.memHeapTotal {"val":35,"ack":true,"ts":1500154523756,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523756}
find-my-iphone.0 | 2017-07-15 23:35:23.756 | debug | redis publish io.system.adapter.find-my-iphone.0.memRss {"val":51.32,"ack":true,"ts":1500154523756,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523756}
find-my-iphone.0 | 2017-07-15 23:35:23.755 | debug | redis publish io.system.adapter.find-my-iphone.0.connected {"val":true,"ack":true,"ts":1500154523755,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:23.755 | debug | redis publish io.system.adapter.find-my-iphone.0.alive {"val":true,"ack":true,"ts":1500154523755,"q":0,"from":"system.adapter.find-my-iphone.0","lc":1500154523755}
find-my-iphone.0 | 2017-07-15 23:35:23.754 | debug | redis keys 1 *.logging
find-my-iphone.0 | 2017-07-15 23:35:23.753 | debug | redis psubscribe io.find-my-iphone.0.checkLogging
find-my-iphone.0 | 2017-07-15 23:35:23.751 | info | starting. Version 0.2.8 in /opt/iobroker/node_modules/iobroker.find-my-iphone, node: v6.11.1
find-my-iphone.0 | 2017-07-15 23:35:23.669 | debug | redis get system.adapter.find-my-iphone.0.alive ok: null
find-my-iphone.0 | 2017-07-15 23:35:23.664 | info | States connected to redis: 127.0.0.1:6379
find-my-iphone.0 | 2017-07-15 23:35:23.661 | debug | statesDB connected
find-my-iphone.0 | 2017-07-15 23:35:23.644 | debug | objectDB connected

`

**Comment by soef** [comment]
There are no outputs form the adapter it self. All outputs are from redis/history.

Can you stop the find-my-iphone adapter on the instances Tab? Then open a shell and change to the iobroker/node_modules/iobroker.find-my-iphone directory. In there type 
node ./iobroker.find-my-ipone.js --force
and watch the outputs on the console.

**Comment by DutchmanNL** [comment]
thank you looking at this issue, i executed the commands as you suggest (first stopped the instance)
the console provides me following error:

root@HomeMaster:/opt/iobroker/node_modules/iobroker.find-my-iphone# node ./iobroker.find-my-ipone.js --force
module.js:471
    throw err;
    ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.find-my-iphone/iobroker.find-my-ipone.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
root@HomeMaster:/opt/iobroker/node_modules/iobroker.find-my-iphone#

**Comment by DutchmanNL** [comment]
update: I adjusted the command to ensure the full path is included, this provides met following result:

root@HomeMaster:/opt/iobroker/node_modules/iobroker.find-my-iphone# node /opt/iobroker/node_modules/iobroker.find-my-iphone/find-my-iphone.js --force
ICloud.prototype.request: path=login
ICloud.prototype.request: statusCode=421 Misdirected Request
ICloud.prototype.request: path=logout
ICloud.prototype.onError: error=Misdirected Request (421)
ICloud.prototype.request: statusCode=421 Misdirected Request
ICloud.prototype.onError: error=Misdirected Request (421)

**Comment by soef** [comment]
Misdirected Request (421).
Can you login into iCloud -> find my iPhone in your browser?

**Comment by DutchmanNL** [comment]
Hi Soef,

Yes i can, just to ensure i did nothing from followed the steps below:

- removed the find my iphone adapter
- installed the adapter again
- provide my mail/pass credentials
- a message came on my phone, i did allow access
- provided the code coming from i cloud to the phone

**Comment by soef** [comment]
I think I found the problem. It should be fixed in version 0.2.9.

**Comment by Apollon77** [comment]
@Dutchmen: Can you please post here if it fixes the problem?

**Comment by DutchmanNL** [comment]
sure will do, the issue is not solved yet.

version 0.2.9 was not provided in iobroker so i did install it from git, after installation i cannot run the adapter anymore maybe i need to force delete it first ?

**Comment by DutchmanNL** [comment]
reinstalled several times, issue is fixed now (at least it looks like)

still see some other issue but will report in a seperat issue post

**Comment by DutchmanNL** [comment]
Hi Soef,

Can we please reopen the issue its not solved sorry :)

After 1 day i have the same issue again, first initiation yesterday was OK but today no date is refresh again and using the force command results in same error as before (adapter is on version 0.2.9)

xxxx@HomeMaster:/opt/iobroker/node_modules/iobroker.find-my-iphone$ sudo node find-my-iphone.js --force
[sudo] password for rafal:
ICloud.prototype.request: path=login
ICloud.prototype.request: statusCode=421 Misdirected Request
ICloud.prototype.request: path=logout
ICloud.prototype.onError: error=Misdirected Request (421)
ICloud.prototype.request: statusCode=421 Misdirected Request
ICloud.prototype.onError: error=Misdirected Request (421)


Adapter    "find-my-iphone": 0.2.8    , installed 0.2.9

**Comment by soef** [comment]
The fixed problem was that the 2 factor key was given to apple not decrypted. So it can't work. 

If it runs yesterday, why does it not run anymore? The adapter hasn't changed. Are there some changes on your apple account? 

btw. the adapter does not refresh the data automaticly. you have to trigger it by changing the refresh state.

**Comment by Apollon77** [comment]
I have the same issue ... installed new version, everything worked, multiple refreshs worked. Nothing changed till then,. Now no refresh is working anymore

**Comment by DutchmanNL** [comment]
@Apollon77 

Did you try the new version 0.2.9 ?
After installation yesterday i received the values for 1 time (which didnt work before).
than i used the refresh button but no updates comming.

See screenshots below were you see the value has been received yesterday and last time i pushed the refresh butto in state overview:

![update](https://user-images.githubusercontent.com/7318445/28494391-5a1b7170-6f2d-11e7-9bc7-fd12f9d93389.JPG)

![refresh](https://user-images.githubusercontent.com/7318445/28494392-5ff2c1a2-6f2d-11e7-8606-b95824537597.JPG)
~Dutch

**Comment by Apollon77** [comment]
Yes, 0.2.9.

**Comment by soef** [comment]
If you are setting the refresh state of a device - not the one in the root - the shouldLocate flag of the request to Apple will be set. So the device will refresh its data and send it back. That can take a while. You can see it by watching the isLocating state. If it is true, the adapter is waiting for an answer.

With the refresh state in the root, all device will only send their aktual data.

**Comment by DutchmanNL** [comment]
it looks like the is refreshing state keeps on true forever ?
I tried the refresh option for my phone and also on the root.

in both cases the value time stays on 2017-07-21 20:42:04.
when using the friends/find my iphone app all looks ok, so still somehow i assume now new data is received from icloud ?

Tried:

- rebooting te adapter
- set flag refresh of the device and wait 15 minutes
- set refresh on root and wait 15 minutes

data keeps the same no new values received :/
